# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:

-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
    #  Analyze your Python requirements for known security vulnerabilities
    -   id: python-safety-dependencies-check
